version: 2.1

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: 
                - main

jobs:
  build:
    working_directory: ~/ExampleApplication-20250204
    docker:
      - image: cimg/node:18.19.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - run:
          name: test-run
          command: npm run test
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  deploy:
    docker:
      - image: cimg/node:18.19.0
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:cK1qEMs2iM5657WX3xTS94zDNt/byLqkveAF/WH6FWw" # Replace with your actual fingerprint from CircleCI
      - run:
          name: Setup SSH Known Hosts
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H $EC2_PUBLIC_DNS >> ~/.ssh/known_hosts
      - run:
          name: Deploy Application
          command: |
            echo "Testing SSH connection:"
            ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "echo 'SSH connection successful'"
            
            echo "Proceeding with deployment:"
            ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "rm -rf ExampleApplication/;git clone https://github.com/SNNCI/ExampleApplication.git; source ExampleApplication/deploy.sh"