version: 2.1

workflows:
    version: 2.1
    build-and-deploy:
        jobs:
            - build:
                filters:
                    branches:
                        only:
                            - main
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: 
                            - main

jobs:
    build:
        working_directory: ~/ExampleApplication-20250204
        docker:
            - image: circleci/node:10.16.3
        steps:
            - checkout
            - run:
                name: update-npm
                command: 'sudo npm install -g npm@5'
            - restore_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
            - run:
                name: install-npm
                command: npm install
            - run:
                name: test-run
                command: npm run test
            - save_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
                paths:
                    - ./node_modules
    deploy:
        docker:
            - image: cimg/node:10.16.3
        steps:
            - checkout
            - add_ssh_keys:
                fingerprints:
                    - "cK1qEMs2iM5657WX3xTS94zDNt/byLqkveAF/WH6FWw"
            - run:
                name: Debug SSH connection
                command: | 
                    ls -la ~/.ssh/
                    ssh -v -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "rm -rf ExampleApplication/;git clone https://github.com/SNNCI/ExampleApplication.git; source ExampleApplication/deploy.sh"
                    
            - run:
                name: deploy-application
                command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "rm -rf ExampleApplication/;git clone https://github.com/SNNCI/ExampleApplication.git; source ExampleApplication/deploy.sh"