version: 2.1

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: 
                - main

jobs:
  build:
    working_directory: ~/ExampleApplication-20250204
    docker:
      - image: cimg/node:18.19.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - run:
          name: test-run
          command: npm run test
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  deploy:
    docker:
      - image: cimg/node:18.19.0
    steps:
      - checkout
      - run:
          name: Setup SSH Key
          command: |
            # Create SSH directory
            mkdir -p ~/.ssh
            
            # Write the private key to a file
            cat > ~/.ssh/id_rsa << 'EOL'
            -----BEGIN RSA PRIVATE KEY-----
            MIIEpAIBAAKCAQEA2+3gwO8E3Vh+i0Kd6uUOvDxD80JAv7DhpxIrMppjXKzOyR1L
            Zs+O+H7ra2+Tn2LoWTYZvl5PlZaxZXCTZf9O8790R1olbMt4cNIzPA/toPHDdaTB
            VliH3YcN/yaQPqq6KRM3TnH9vkELYS8Mn8F6iiavDnHXDwpnd3ggrdsoLqbP9s4O
            aY/5cBvNQlMJcpW09yEJn5d64W74sJdkGEr7uLUd8bZnXtEjx2sjDK5n2fDTNxgm
            gu4lfHVxnc9f4lSJlXul33bsxV7LDu0VGU7aBFlZsg6TkErdQ3OgdQxaN00GQkB+
            +rI9JpRhRcwlT2r5XZFOJbaXSM3DxqSGi+y+rwIDAQABAoIBAFLLWrFHSi2KAxmq
            Gokzcjiq92m8p2OC03ByBpEmTgG1jKNpw9kQimJCZZ4sgwad1ZrAIzDnkE5gTKhD
            mTnsw2w/xyaVaUFr2AuhFmimFm9glJTVUXOQIJXlIf/MJMFyxGJyOX/uqffVxNLx
            Q29hByC7L2vgr3WaFRmEv8izmIz2zOu+reAZIGFGbaBXf7byEuTwCcmjaylXy83j
            QYgo0ZV1t33A2fsOREktwg2Scf/ZOX0Lvquzws3rzXpggEmmp8XDn+bCsLRSlvOZ
            vMZeaDMmuQmzfPgC7Eb4yTmoWvVwcfYTqffz12toQQBq+1jom3CO6FtnhloEXoAN
            J1UFAgECgYEA7g0i2yDzTNF+8JaFEeEvFxYWr414XAXMRS/plmiwmONBVkKduepb
            85KtA8ZcQV3Wn8Gg9DEum5hmgclRO1hEOPRoG9VnBc4+UJuv6eSG1akBy1y6WpqJ
            vVkT+QDEusWG7Ab8mPNBTILHHcwCnjBvTtmZXjggsieUiPNTGWIy9okCgYEA7ILy
            /IKlTWIcipaARR1V6a02XCDtGWm3ZmlHtVQviQkslwEwVoD9VHybeU4Tu2EXSCVj
            +59A4dzvG+1AG3gPzViS+3zrd36QQfCTVAuop4lXGPQ+kiiOnFOTnaJAGqcdBOnb
            o4BTOrEWLsysBUEkS5/Aj4fRT7KLUgWqquYxvXcCgYEA0Pa1BzgoeuFXlef7TdOn
            G5PnPBlqcxUf2AgT+1VQ2BR9UTRO8ll4eBrkR3EDoNm3wisdl93odOtV6E4JQZfc
            40YgcXZl5iHCb84KoL1bYwjlq1dtuoT3rkAYmTcEepNUObJ0X+sBAiG2mkBwd946
            hzPaPmv0v46hA4rdAmZCKEkCgYBwtuOYZabj3ysc/Sa6SYXFLLBobaSxZMlrvCbZ
            ivpwg3fFq2JfB3Az0ILD5+rNdTMERhWFOFtSiNlHZOUVcj2NrnW19s29EAst8bo0
            5q2E0pY4pUYgn8V/SPFjwYxtZ1EUI2NyY1jG8thQi2g7xNTIWaUKgj7FjaCKAXtZ
            oQT5dwKBgQC4jcnrod7r0ElOXEy6jKuXPmWTnXEHuQBCQmobzLmaQ4UYp8WnK86b
            FuQSxlxeVmoNffJo1lBsY5i8LjnCIXdCP4ox6GIQGBFfcDnw2CHRkvTv4TOfKWAI
            ebsE4qO4PSfeRncTR+tGj4krSn3r4v7IxwoUnOLW2BY3rnE63P6dlQ==
            -----END RSA PRIVATE KEY-----
            EOL
            
            # Set proper permissions
            chmod 600 ~/.ssh/id_rsa
            
            # Check that the key is valid
            echo "Key file permissions and content:"
            ls -la ~/.ssh/id_rsa
            
            # Add server to known hosts
            ssh-keyscan -H $EC2_PUBLIC_DNS >> ~/.ssh/known_hosts
            
            # Display MD5 fingerprint for reference (CircleCI uses this format)
            echo "MD5 fingerprint:"
            ssh-keygen -E md5 -lf ~/.ssh/id_rsa
            
            # Display SHA256 fingerprint for reference (what you've seen)
            echo "SHA256 fingerprint (should match your SHA256:cK1qEMs2iM5657WX3xTS94zDNt/byLqkveAF/WH6FWw):"
            ssh-keygen -lf ~/.ssh/id_rsa
      - run:
          name: Deploy Application
          command: |
            echo "Testing SSH connection:"
            ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "echo 'SSH connection successful'"
            
            echo "Proceeding with deployment:"
            ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "rm -rf ExampleApplication/;git clone https://github.com/SNNCI/ExampleApplication.git; source ExampleApplication/deploy.sh"